[sections.blog]
plugin = "feed"
url = "https://meiert.com/en/feed/"
n = 10
show_date = true
prepend_text = "## From [My Blog](https://meiert.com/)\n\n"

[sections.last_updated]
plugin = "current_date"
inline = true