name: "Metrics: Full-Year Calendar"
uses: lowlighter/metrics@latest
with:
  filename: github-metrics.plugin.isocalendar.fullyear.svg
  token: ${{ secrets.METRICS }}
  base: ""
  plugin_isocalendar: yes
  plugin_isocalendar_duration: full-year