name: "Metrics"

on:
  schedule:
    # Schedule twice-weekly updates (offset avoids top-of-hour queue spikes)
    # https://crontab.guru/
    - cron: "17 4 * * 1,4"
  # (optional) Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6
        with:
          token: ${{ secrets.METRICS }}
      - name: "Calendar"
        uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6
        with:
          filename: github-metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year